name: Publish client

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: "@arthurzakharov"
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun run client:verify
        env:
          CLIENT_VERSION: ${{ github.ref_name }}
      - run: npm publish
        working-directory: dist-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
